name: Build and Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up build environment
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential devscripts debhelper

    - name: Extract version from tag
      id: version
      run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

    - name: Update VERSION file
      run: echo "${{ steps.version.outputs.VERSION }}" > VERSION

    - name: Make build scripts executable
      run: |
        chmod +x build/build-linux.sh
        chmod +x build/build-opnsense.sh

    - name: Build Linux DEB package
      run: ./build/build-linux.sh

    - name: Build OPNsense package
      run: ./build/build-opnsense.sh

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.ref_name }}
        name: Release ${{ steps.version.outputs.VERSION }}
        body: IPSet Blacklist Service v${{ steps.version.outputs.VERSION }} - Multi-source blacklist management for Linux and OPNsense with Check_MK monitoring integration.
        files: |
          build/linux/ipset-blacklist-service_${{ steps.version.outputs.VERSION }}_all.deb
          build/opnsense/ipset-blacklists-opnsense.tar.gz
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
